"""
PDF Generation Utilities
Supports WeasyPrint (preferred) and ReportLab (fallback)
"""
import os
from datetime import datetime
from django.conf import settings
from PyPDF2 import PdfMerger
import logging

logger = logging.getLogger(__name__)

def generate_member_pdf_weasyprint(text_content, member_email, task_title, output_path):
    """Generate PDF using WeasyPrint"""
    try:
        from weasyprint import HTML, CSS
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                @page {{
                    size: A4;
                    margin: 2cm;
                }}
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                .header {{
                    border-bottom: 2px solid #2563eb;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }}
                .header h1 {{
                    color: #2563eb;
                    margin: 0;
                    font-size: 24px;
                }}
                .meta {{
                    color: #666;
                    font-size: 12px;
                    margin-top: 10px;
                }}
                .content {{
                    white-space: pre-wrap;
                    word-wrap: break-word;
                }}
                .footer {{
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    font-size: 10px;
                    color: #999;
                    text-align: center;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{task_title}</h1>
                <div class="meta">
                    <p><strong>Submitted by:</strong> {member_email}</p>
                    <p><strong>Date:</strong> {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
                </div>
            </div>
            <div class="content">
                {text_content}
            </div>
            <div class="footer">
                <p>Generated by Classroom Management System</p>
            </div>
        </body>
        </html>
        """
        
        HTML(string=html_content).write_pdf(output_path)
        logger.info(f"PDF generated with WeasyPrint: {output_path}")
        return True
        
    except Exception as e:
        logger.error(f"WeasyPrint error: {e}")
        return False

def generate_member_pdf_reportlab(text_content, member_email, task_title, output_path):
    """Generate PDF using ReportLab (fallback)"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.enums import TA_LEFT
        
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor='#2563eb',
            spaceAfter=20,
        )
        story.append(Paragraph(task_title, title_style))
        
        # Meta information
        meta_style = ParagraphStyle(
            'Meta',
            parent=styles['Normal'],
            fontSize=10,
            textColor='#666666',
        )
        story.append(Paragraph(f"<b>Submitted by:</b> {member_email}", meta_style))
        story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y at %H:%M')}", meta_style))
        story.append(Spacer(1, 0.3 * inch))
        
        # Content
        content_style = ParagraphStyle(
            'Content',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
        )
        
        # Split content into paragraphs
        paragraphs = text_content.split('\n')
        for para in paragraphs:
            if para.strip():
                story.append(Paragraph(para, content_style))
                story.append(Spacer(1, 0.1 * inch))
        
        # Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor='#999999',
            alignment=TA_LEFT,
        )
        story.append(Paragraph("Generated by Classroom Management System", footer_style))
        
        doc.build(story)
        logger.info(f"PDF generated with ReportLab: {output_path}")
        return True
        
    except Exception as e:
        logger.error(f"ReportLab error: {e}")
        return False

def generate_member_pdf(text_content, member_email, task_title, filename=None):
    """
    Generate PDF for member submission
    Tries WeasyPrint first, falls back to ReportLab
    """
    if not filename:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_email = member_email.split('@')[0].replace('.', '_')
        filename = f"{safe_email}_{timestamp}.pdf"
    
    # Ensure submissions directory exists
    submissions_dir = os.path.join(settings.MEDIA_ROOT, 'submissions')
    os.makedirs(submissions_dir, exist_ok=True)
    
    output_path = os.path.join(submissions_dir, filename)
    
    # Try WeasyPrint first
    if generate_member_pdf_weasyprint(text_content, member_email, task_title, output_path):
        return output_path
    
    # Fallback to ReportLab
    logger.warning("WeasyPrint failed, using ReportLab fallback")
    if generate_member_pdf_reportlab(text_content, member_email, task_title, output_path):
        return output_path
    
    logger.error("Both PDF generation methods failed")
    return None

def compile_group_pdf(submission_paths, group_name, task_title, output_filename=None):
    """
    Compile multiple member PDFs into one group PDF
    """
    if not submission_paths:
        logger.error("No submission paths provided for compilation")
        return None
    
    if not output_filename:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_group = group_name.replace(' ', '_')
        output_filename = f"{safe_group}_{timestamp}.pdf"
    
    # Ensure compiled directory exists
    compiled_dir = os.path.join(settings.MEDIA_ROOT, 'compiled')
    os.makedirs(compiled_dir, exist_ok=True)
    
    output_path = os.path.join(compiled_dir, output_filename)
    
    try:
        merger = PdfMerger()
        
        for pdf_path in submission_paths:
            if os.path.exists(pdf_path):
                merger.append(pdf_path)
            else:
                logger.warning(f"PDF file not found: {pdf_path}")
        
        merger.write(output_path)
        merger.close()
        
        logger.info(f"Compiled PDF created: {output_path}")
        return output_path
        
    except Exception as e:
        logger.error(f"Error compiling PDFs: {e}")
        return None

def get_submission_pdf_path(pdf_relative_path):
    """Get full path for a submission PDF"""
    if not pdf_relative_path:
        return None

    media_url = getattr(settings, 'MEDIA_URL', '/media/')

    if os.path.isabs(pdf_relative_path):
        if pdf_relative_path.startswith(media_url):
            normalized_path = pdf_relative_path[len(media_url):].lstrip('/')
        else:
            return pdf_relative_path
    else:
        normalized_path = pdf_relative_path.lstrip('/')

    if normalized_path.startswith('media/'):
        normalized_path = normalized_path[len('media/'):]

    if normalized_path.startswith('media/'):
        normalized_path = normalized_path[len('media/'):]

    return os.path.join(settings.MEDIA_ROOT, normalized_path)